Scriptable object exercice
Logan-dlp/Logan-2emeAnnee-EartsupUnity pull request #2
Opened 2023-10-09 18:58 UTC by Logan-dlp

2023-10-09 20:48 UTC, GuitoonDev requested changes
Tu as rajouté la méthode qui crée les cartes en tant qu'asset mais tu ne t'en ai pas servi. Si c'était le cas, je verrais des assets pour chaque carte d'un jeu classique dans ton projet.

N'hésite pas à me demander si tu as besoin de précisions sur l'énoncé ou s'il ne te parait pas assez clair.

2023-10-09 20:48 UTC, GuitoonDev commented on Assets/_Core/ExoScriptableObject/Scripts/CardInstanciator.cs
> +                if (cardItem.CardValue == newCardData.CardValue && cardItem.CardSign == newCardData.CardSign) return;
Ecrire la totalité d'un bloc if sur une seule ligne n'est pas une écriture recommandé.

De plus ça ne respecte pas la règle 8 des conventions d'écriture.

2023-10-09 20:48 UTC, GuitoonDev commented on Assets/_Core/ExoScriptableObject/Scripts/CardInstanciator.cs
> +        }else Debug.LogError("You did not draw your 7 cards !");
Ne respecte pas la règle 8 des conventions d'écriture.

2023-10-09 20:48 UTC, GuitoonDev commented on Assets/_Core/ExoScriptableObject/Scripts/CardInstanciator.cs
> +    private void CreateAssetFromDeck()
Ok tu as fait une méthode pour créer des cartes en tant qu'asset mais dans son fonctionnement actuel elle ne crée aucune carte dans le projet (sauf une fois le runtime lancé et seulement pour 7 cartes).

La première partie de l'énoncé de l'exercice n'est pas encore remplie.

2023-10-09 20:48 UTC, GuitoonDev commented on Assets/_Core/ExoScriptableObject/Scripts/CardInstanciator.cs
> +                AssetDatabase.CreateAsset(cardItem, "Assets/_Core/ExoScriptableObject/Scripts/Data/" + cardItem.CardValue.ToString() + "_" + cardItem.CardSign.ToString() + ".asset");
Je te déconseille fortement de mettre autre chose que des scripts dans ton dossier `Scripts`. Quel est le sens de la logique de rangement de ton projet si tu mets des ScriptableObjects dans ton dossier `Scripts` ?

2023-10-09 20:48 UTC, GuitoonDev commented on Assets/_Core/ExoScriptableObject/Scripts/CardData.cs
> +    Tile,
C'est pas une traduction fausse mais dans un jeu de cartes, le terme anglais pour "Carreau" c'est "Diamond".

2023-10-09 20:48 UTC, GuitoonDev commented on Assets/_Core/ExoScriptableObject/Scripts/CardData.cs
> +    Clover,
Pareil pour "Trèfle" qui devient "Club"

2023-10-09 20:48 UTC, GuitoonDev commented on Assets/_Core/ExoScriptableObject/Scripts/CardData.cs
> +    Pike,
Pareil pour "Pique" qui devient "Spade"

2023-10-17 13:24 UTC, GuitoonDev submitted a review, later dismissed
Il y a du mieux et de la prise en compte des retours mais l’exercice n'est toujours pas résolu intégralement. Je te remets le point de l'exercice qu'il manque dans ton projet :
- Créer un jeu de cartes traditionnel dans un projet unity avec au moins la couleur et la valeur dans chacune

Sous-entendu : Il te faut dans un dossier dans lequel chaque carte du jeu de 52 cartes doit être un scriptable object. Pas juste générer en scriptable object les 7 cartes piochées.

2023-10-17 13:24 UTC, GuitoonDev commented on Assets/_Core/ExoScriptableObject/Scripts/CardInstanciator.cs
> +                AssetDatabase.CreateAsset(cardItem, "Assets/_Core/ExoScriptableObject/SciptableObject_Data/" + cardItem.CardValue.ToString() + "_" + cardItem.CardSign.ToString() + ".asset");
Pourquoi juste nommer le dossier `Datas` ?
En vrai, je pense que ça n'est pas faux mais j'aimerais savoir pourquoi tu l'as nommé comme ça.

De manière générale, il vaut mieux éviter les répétitions des noms des dossiers parents dans les noms des dossiers.

2023-10-17 13:24 UTC, GuitoonDev commented on Assets/_Core/ExoScriptableObject/Scripts/CardInstanciator.cs
> +                    return;
A cause de cette ligne, ton code ne tire pas 7 cartes de façon stable à chaque exécution
![image](https://github.com/Logan-dlp/Logan-2emeAnnee-EartsupUnity/assets/32094695/ffe0ed69-37a4-4bc6-b267-34f3eda50702)

2023-10-25 12:45 UTC, GuitoonDev requested changes
Désolé mais il n'y a toujours pas les cartes en tant qu'asset dans le projet. Chaque carte du jeu doit être représenté par un asset. Actuellement, lorsque je lance le Play, j'ai une erreur dans la console :
![image](https://github.com/Logan-dlp/Logan-2emeAnnee-EartsupUnity/assets/32094695/375f4051-81bb-4acd-9116-50f7f4027f1d)

Ton projet devrait ressembler à une structure du genre :
![image](https://github.com/Logan-dlp/Logan-2emeAnnee-EartsupUnity/assets/32094695/1cdd01fd-874c-4438-bc70-7a5129967d7c)
De cette façon, chacune des cartes du jeu existent en tant qu'asset dans ton projet.

Je reste disponible pour discuter de toutes précisions que je peux apporter à l'énoncé pour t'aider à la résolution de l'exercice. N'hésite surtout pas !

2023-10-25 12:45 UTC, GuitoonDev commented on Assets/_Core/ExoScriptableObject/Scripts/CardInstanciator.cs
> +using Unity.VisualScripting;
Je pense que ce namespace n'est pas nécessaire.

2023-11-01 09:46 UTC, GuitoonDev approved these changes
Ok, l'énoncé est respecté.

En améliorations possible, le mieux serait de créer les cartes sans avoir à lancer le mode play. Il existe un attribut à placer sur une fonction qui permet de l’exécuter directement en éditeur.

Je te donne un premier lien qui va t'orienter dans ta recherche mais ça sera à toi de le trouver :
https://docs.unity3d.com/Manual/Attributes.html

PS : Et retire moi ces namespaces inutiles dans ton code surtout !

2023-11-01 09:46 UTC, GuitoonDev commented on Assets/_Core/ExoScriptableObject/Scripts/CardInstanciator.cs
> +        foreach (object nameFolderObject in Enum.GetValues(typeof(Sign)))
Actuellement, tu fais trois boucles pour créer tes cartes mais tu peux le faire en deux.

2023-11-01 09:46 UTC, GuitoonDev commented on Assets/_Core/ExoScriptableObject/Scripts/CardInstanciator.cs
> +                AssetDatabase.CreateAsset(newCardAssetInstance, "Assets/_Core/ExoScriptableObject/ScriptableObject_Data/" + newCardAssetInstance.CardSign.ToString() + "s/" + newCardAssetInstance.Card
Attention aux lignes trop longues. N'hésite pas à faire des variables intermédiaires pour équilibrer la taille de tes lignes.

2023-11-01 16:58 UTC, Logan-dlp commented
J'ai essayer de le faire avec deux boucle mais (pour ça que j'ai changer l'ordre entre sign et value) mais cela me retourner un erreur et la méthode ne voulais pas s'exécuter correctement.

2023-11-05 11:47 UTC, GuitoonDev commented
> J'ai essayer de le faire avec deux boucle mais (pour ça que j'ai changer l'ordre entre sign et value) cela me retourner un erreur et la méthode ne voulais pas s'exécuter correctement.

On regardera ça parce que ça n'est pas opti de boucler deux fois sur `Sign`

2023-11-05 14:12 UTC, GuitoonDev commented on Assets/_Core/ExoScriptableObject/Scripts/CardInstanciator.cs
> +            AssetDatabase.Refresh();
Pourquoi faire un refresh à chaque tour de boucle ?
Vu que tous les dossiers sont créés au même moment, autant refresh une fois tous les dossiers créés non ?

2023-11-05 14:12 UTC, GuitoonDev approved these changes

2023-12-24 10:53 UTC, merged