Event Exercice
Logan-dlp/Logan-2emeAnnee-EartsupUnity pull request #3
Opened 2023-10-11 15:03 UTC by Logan-dlp

2023-10-17 13:12 UTC, GuitoonDev approved these changes
Ok ça fonctionne pas de problème mais quelques petits retours.

2023-10-17 13:12 UTC, GuitoonDev commented on Assets/_Core/Event/ExoEvent/Scripts/CharacterBehaviour.cs
> +    private int _health = 100;
[Ne respecte pas la règle n°3 des conventions d'écriture](https://pastebin.com/ZbTgSgNx)

2023-10-17 13:12 UTC, GuitoonDev commented on Assets/_Core/Event/ExoEvent/Scripts/HealthBar.cs
> +        _image = GetComponent<Image>();
Dans le cas actuel du script, tu n'as aucune garantie que le `GetComponent` renvoie à coup sûr quelque chose. Il manque une ligne pour éviter un retour `null`

2023-10-17 13:12 UTC, GuitoonDev commented on Assets/_Core/Event/ExoEvent/Scripts/HealthBar.cs
> +        _image.fillAmount = (float)newHealth * .01f;
Tu n'as pas besoin de faire un cast sur `newHealth` si la seconde valeur est déjà en `float`. Ce qui est le cas puisque tu as rajouté un `f` à ta valeur.

2023-10-17 13:12 UTC, GuitoonDev commented on Assets/_Core/Event/ExoEvent/Scripts/CharacterBehaviour.cs
> +[RequireComponent(typeof(Rigidbody)), RequireComponent(typeof(Collider))]
Il faut éviter de répéter le même attribut. Tu peux mettre plusieurs types en paramètres d'un `RequireComponent`.
(Voir la documentation)

2023-10-20 17:36 UTC, Logan-dlp commented on Assets/_Core/Event/ExoEvent/Scripts/HealthBar.cs
> +        _image = GetComponent<Image>();
Un RequireComponent pourrait faire l'affaire ?

2023-10-20 17:46 UTC, Logan-dlp commented on Assets/_Core/Event/ExoEvent/Scripts/CharacterBehaviour.cs
> +    private int _health = 100;
C'est le nom de la variable qui ne respecte pas ? je devrais plutôt l'appeler _healthInt ?

2023-10-23 08:41 UTC, GuitoonDev commented on Assets/_Core/Event/ExoEvent/Scripts/CharacterBehaviour.cs
> +    private int _healthInt = 100;
Le nom que tu avais avant été bien. Là je pense que la précision est peut-être un peu trop.
Ou alors, si vraiment tu veux lever une ambigüité, je verrais bien plutôt `_healthValue`.

2023-10-23 08:46 UTC, GuitoonDev requested changes
Certains changements partent d'une bonne intention mais ne vont pas dans le bon sens.

2023-10-23 08:46 UTC, GuitoonDev commented on Assets/_Core/Event/ExoEvent/Scripts/HealthBar.cs
> +    private void HealthChanged(float newHealth)
ça n'est pas ce que je voulais dire.
Tu peux laisser `newHealth` en `int` et faire l'opération avec un `float` renvoie un résultat en `float`.

2023-10-23 08:46 UTC, GuitoonDev commented on Assets/_Core/Event/ExoEvent/Scripts/ScriptableEventInt.cs
> +    public Action<float> Event;
Pourquoi un `ScriptableEventInt` renvoie un `float` ?

Attention à la cohérence de ton code.

2023-11-01 09:49 UTC, GuitoonDev approved these changes
Ok, c'est bon pour moi.

2023-11-02 16:58 UTC, merged