Buffer Shader & Bubule gum
Logan-dlp/Logan-2emeAnnee-EartsupUnity pull request #8
Opened 2024-01-23 14:30 UTC by Logan-dlp

2024-01-30 21:17 UTC, GuitoonDev requested changes
Je ne valide pas car j'ai des doutes sur 3 shaders.

Mais la plupart sont très proches du résultat attendu.

2024-01-30 21:17 UTC, GuitoonDev commented on Assets/_Core/Shader/ExoShader/Shaders/FireBall.shader
> +                OUT.uv.y = OUT.uv.y + _Time.x;
Je ne vois pas d'intérêt à placer cette ligne dans le vertex shader.

2024-01-30 21:17 UTC, GuitoonDev commented on Assets/_Core/Shader/ExoShader/Shaders/Bubule.shader
> +                float1 lerpFactor = .5 + .5 * sin(_Time.y * _FlashFrequency);
Oui `float1` existe de fait mais c'est un `float`, je ne comprends pas l'intérêt de l'appeler `float1`

2024-01-30 21:17 UTC, GuitoonDev commented on Assets/_Core/Shader/ExoShader/Shaders/FireBall.shader
> +                half4 fresnelColor = _RimColor + (1 - fresnel) * textureColor;
Pourquoi la couleur de la texture rentre dans le calcul de la couleur du fresnel ?

2024-01-30 21:17 UTC, GuitoonDev commented on Assets/_Core/Shader/ExoShader/Shaders/Sphere.shader
> +                textureColor = lerp(textureColor, invertTextureColor, _BuffPower) + color;
Le calcul ici n'est pas bon, si tu rajoutes une valeur de couleur au lerp, tu n'as pas le résultat du lerp strictement.

2024-01-30 21:17 UTC, GuitoonDev commented on Assets/_Core/Shader/ExoShader/Shaders/Chessboard.shader
> +                float1 y = round(frac(IN.uv.y * _RepeatValue));
Autant les renommer `float`.

2024-01-30 21:17 UTC, GuitoonDev commented on Assets/_Core/Shader/ExoShader/Shaders/Bubule.shader
> +                float1 lerpFactor = .5 + .5 * sin(_Time.y * _FlashFrequency);
Tu as une variable `lerpFactor` mais tu ne fais pas de `lerp` avec ?
C'est quoi ton calcul ligne 79 du coup ?

2024-01-31 13:53 UTC, GuitoonDev commented on Assets/_Core/Shader/ExoShader/Shaders/FireBall.shader
> +                return color + fresnel * fresnelColor;
La couleur finale doit être l'addition que de deux couleurs : celle de la texture et celle du fresnel

2024-03-01 08:34 UTC, Logan-dlp commented on Assets/_Core/Shader/ExoShader/Shaders/Sphere.shader
> +                textureColor = lerp(textureColor, invertTextureColor, _BuffPower) + color;
Je devrais plutôt multiplier ducoup ?

2024-03-03 15:06 UTC, GuitoonDev requested changes

2024-03-03 15:06 UTC, GuitoonDev commented on Assets/_Core/Shader/ExoShader/Shaders/FireBall.shader
> +                half4 fresnelColor = _RimColor + (1 - fresnel);
Normalement, un effet de fresnel ajoute une couleur d'abord sur les contours du modèle mais le tien, plus ton `_FresnelPower` est élevé, plus il colore d'abord l'intérieur du modèle.
![image](https://github.com/Logan-dlp/Logan-2emeAnnee-EartsupUnity/assets/32094695/5d7ee37c-854d-408e-9599-2b087303bb5b)

2024-03-03 15:06 UTC, GuitoonDev commented on Assets/_Core/Shader/ExoShader/Shaders/Bubule.shader
Le shader prévoit une couleur lorsque le modèle atteint sa taille maximale et une autre couleur lorsqu'il est à la taille minimale.

Actuellement, dans ta version, la variation entre les deux couleurs peuvent varier indépendamment de la taille alors que ça ne doit pas être le cas.

Pour préciser les variables :
- `_FlashFrequency` définit la vitesse à laquelle le modèle oscille entre sa taille max et sa taille min.
- `_Displacement` définit la taille maximale de la déformation par rapport à la taille de base du modèle (plus la valeur est grande, plus la sphère sera grosse dans sa taille max).

2024-03-21 22:41 UTC, GuitoonDev approved these changes

2024-03-21 22:41 UTC, GuitoonDev commented on Assets/_Core/Shader/ExoShader/Shaders/FireBall.shader
>                  return fresnelColor * textureColor;
Maintenant, on voit mieux qu'avec la multiplication, les deux couleurs se mélangent trop et le fresnel ne se voit pas assez.

2024-03-22 07:45 UTC, GuitoonDev approved these changes
Je viens de comprendre le calcul du shader de buff, désolé. Du coup, ça fait deux shaders finis je valide.

2024-03-22 08:57 UTC, merged